//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMSDataAccessLayer
{
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel;
    using TrackableEntities;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Runtime.Serialization;
    using System.Collections.ObjectModel;

    using System;
    using System.Collections.Generic;
    using TrackableEntities.Client;
    
    public partial class ItemDosage : BaseEntity<ItemDosage>
    {
        [DataMember]
                    [Required(ErrorMessage="ItemId is required")]
    	public int ItemId
    	{ 
    		get { return _ItemId; }
    		set
    		{
    			if (Equals(value, _ItemId)) return;
    			_ItemId = value;
                ValidateModelProperty(this, value);
    			NotifyPropertyChanged();
    		}
    	}
    	private int _ItemId;
        [DataMember]
                    [Required(ErrorMessage="Dosage is required")]
    	public string Dosage
    	{ 
    		get { return _Dosage; }
    		set
    		{
    			if (Equals(value, _Dosage)) return;
    			_Dosage = value;
                ValidateModelProperty(this, value);
    			NotifyPropertyChanged();
    		}
    	}
    	private string _Dosage;
        [DataMember]
        	public Nullable<int> Count
    	{ 
    		get { return _Count; }
    		set
    		{
    			if (Equals(value, _Count)) return;
    			_Count = value;
                ValidateModelProperty(this, value);
    			NotifyPropertyChanged();
    		}
    	}
    	private Nullable<int> _Count;
    }
}
