//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMSDataAccessLayer
{
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel;
    using TrackableEntities;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Runtime.Serialization;
    using System.Collections.ObjectModel;

    using System;
    using System.Collections.Generic;
    using TrackableEntities.Client;
    
    public partial class PrescriptionEntry : TransactionEntryBase
    {
        
        public PrescriptionEntry()
        {
            this.Repeat = 0;
            CustomStartup();
            this.PropertyChanged += UpdatePropertyChanged;
            
        }
        partial void CustomStartup();
    
            private void UpdatePropertyChanged(object sender, PropertyChangedEventArgs e)
            {
                if (!string.IsNullOrEmpty(e.PropertyName) && (!Environment.StackTrace.Contains("Internal.Materialization")) && TrackingState == TrackingState.Unchanged)
                {
                    TrackingState = TrackingState.Modified;
                }
            }
    
            ChangeTrackingCollection<PrescriptionEntry> _changeTracker;
    
            [NotMapped]
            [IgnoreDataMember]
            public ChangeTrackingCollection<PrescriptionEntry> ChangeTracker
            {
                get
                {
                    return _changeTracker;
                }
            }
            
            public new void StartTracking()
            {
                _changeTracker = new ChangeTrackingCollection<PrescriptionEntry>(this);
            }
        [DataMember]
        	public string Dosage
    	{ 
    		get { return _Dosage; }
    		set
    		{
    			if (Equals(value, _Dosage)) return;
    			_Dosage = value;
                ValidateModelProperty(this, value);
    			NotifyPropertyChanged();
    		}
    	}
    	private string _Dosage;
        [DataMember]
        	public Nullable<System.DateTime> ExpiryDate
    	{ 
    		get { return _ExpiryDate; }
    		set
    		{
    			if (Equals(value, _ExpiryDate)) return;
    			_ExpiryDate = value;
                ValidateModelProperty(this, value);
    			NotifyPropertyChanged();
    		}
    	}
    	private Nullable<System.DateTime> _ExpiryDate;
        [DataMember]
        	public Nullable<int> Repeat
    	{ 
    		get { return _Repeat; }
    		set
    		{
    			if (Equals(value, _Repeat)) return;
    			_Repeat = value;
                ValidateModelProperty(this, value);
    			NotifyPropertyChanged();
    		}
    	}
    	private Nullable<int> _Repeat;
    }
}
